export const STATES = [
	{ value: "alabama", label: "Alabama" },
	{ value: "alaska", label: "Alaska" },
	{ value: "arizona", label: "Arizona" },
	{ value: "arkansas", label: "Arkansas" },
	{ value: "california", label: "California" },
	{ value: "colorado", label: "Colorado" },
	{ value: "connecticut", label: "Connecticut" },
	{ value: "delaware", label: "Delaware" },
	{ value: "florida", label: "Florida" },
	{ value: "georgia", label: "Georgia" },
	{ value: "hawaii", label: "Hawaii" },
	{ value: "idaho", label: "Idaho" },
	{ value: "illinois", label: "Illinois" },
	{ value: "indiana", label: "Indiana" },
	{ value: "iowa", label: "Iowa" },
	{ value: "kansas", label: "Kansas" },
	{ value: "kentucky", label: "Kentucky" },
	{ value: "louisiana", label: "Louisiana" },
	{ value: "maine", label: "Maine" },
	{ value: "maryland", label: "Maryland" },
	{ value: "massachusetts", label: "Massachusetts" },
	{ value: "michigan", label: "Michigan" },
	{ value: "minnesota", label: "Minnesota" },
	{ value: "mississippi", label: "Mississippi" },
	{ value: "missouri", label: "Missouri" },
	{ value: "montana", label: "Montana" },
	{ value: "nebraska", label: "Nebraska" },
	{ value: "nevada", label: "Nevada" },
	{ value: "new hampshire", label: "New Hampshire" },
	{ value: "new jersey", label: "New Jersey" },
	{ value: "new mexico", label: "New Mexico" },
	{ value: "new york", label: "New York" },
	{ value: "north carolina", label: "North Carolina" },
	{ value: "north dakota", label: "North Dakota" },
	{ value: "ohio", label: "Ohio" },
	{ value: "oklahoma", label: "Oklahoma" },
	{ value: "oregon", label: "Oregon" },
	{ value: "pennsylvania", label: "Pennsylvania" },
	{ value: "rhode island", label: "Rhode Island" },
	{ value: "south carolina", label: "South Carolina" },
	{ value: "south dakota", label: "South Dakota" },
	{ value: "tennessee", label: "Tennessee" },
	{ value: "texas", label: "Texas" },
	{ value: "utah", label: "Utah" },
	{ value: "vermont", label: "Vermont" },
	{ value: "virginia", label: "Virginia" },
	{ value: "washington", label: "Washington" },
	{ value: "west virginia", label: "West Virginia" },
	{ value: "wisconsin", label: "Wisconsin" },
	{ value: "wyoming", label: "Wyoming" },
]

export const SHORT_LABEL_STATES = [
	{ value: "alabama", label: "AL" },
	{ value: "alaska", label: "AK" },
	{ value: "arizona", label: "AZ" },
	{ value: "arkansas", label: "AR" },
	{ value: "california", label: "CA" },
	{ value: "colorado", label: "CO" },
	{ value: "connecticut", label: "CT" },
	{ value: "delaware", label: "DE" },
	{ value: "florida", label: "FL" },
	{ value: "georgia", label: "GA" },
	{ value: "hawaii", label: "HI" },
	{ value: "idaho", label: "ID" },
	{ value: "illinois", label: "IL" },
	{ value: "indiana", label: "IN" },
	{ value: "iowa", label: "IA" },
	{ value: "kansas", label: "KS" },
	{ value: "kentucky", label: "KY" },
	{ value: "louisiana", label: "LA" },
	{ value: "maine", label: "ME" },
	{ value: "maryland", label: "MD" },
	{ value: "massachusetts", label: "MA" },
	{ value: "michigan", label: "MI" },
	{ value: "minnesota", label: "MN" },
	{ value: "mississippi", label: "MS" },
	{ value: "missouri", label: "MO" },
	{ value: "montana", label: "MT" },
	{ value: "nebraska", label: "NE" },
	{ value: "nevada", label: "NV" },
	{ value: "new hampshire", label: "NH" },
	{ value: "new jersey", label: "NJ" },
	{ value: "new mexico", label: "NM" },
	{ value: "new york", label: "NY" },
	{ value: "north carolina", label: "NC" },
	{ value: "north dakota", label: "ND" },
	{ value: "ohio", label: "OH" },
	{ value: "oklahoma", label: "OK" },
	{ value: "oregon", label: "OR" },
	{ value: "pennsylvania", label: "PA" },
	{ value: "rhode island", label: "RI" },
	{ value: "south carolina", label: "SC" },
	{ value: "south dakota", label: "SD" },
	{ value: "tennessee", label: "TN" },
	{ value: "texas", label: "TX" },
	{ value: "utah", label: "UT" },
	{ value: "vermont", label: "VT" },
	{ value: "virginia", label: "VA" },
	{ value: "washington", label: "WA" },
	{ value: "west virginia", label: "WV" },
	{ value: "wisconsin", label: "WI" },
	{ value: "wyoming", label: "WY" },
]
