import "@/styles/index.scss";
import { Inter, Poppins } from "next/font/google";
import { Providers } from "./GlobalObjects/store/Providers";
import "./globals.css";
import Help from "@/components/common/Modals/Help";
import Logout from "@/components/common/Modals/Logout";
import PrePatientRegister from "@/components/common/Modals/PrePatientRegister";

// const inter = Inter({
//   weight: ["400", "500", "600", "700", "800", "900"],
//   subsets: ["latin"],
//   variable: "--font-inter",
//   style: ["normal"],
// });
// const poppins = Poppins({
//   weight: ["400", "500", "600", "700", "800", "900"],
//   subsets: ["latin"],
//   variable: "--font-poppins",
//   style: ["normal", "italic"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <Help />
          <Logout />
          <PrePatientRegister />
        </Providers>
      </body>
    </html>
  );
}
